In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('../Datasets/Training.csv')

In [4]:
data

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [5]:
X=data.drop('prognosis', axis=1)
y=data['prognosis']

In [6]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [7]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [11]:
from sklearn.model_selection import train_test_split 

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=30)

In [14]:
X_test.shape,X_train.shape,y_test.shape,y_train.shape

((1476, 132), (3444, 132), (1476,), (3444,))

In [8]:
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier

In [18]:
 models = {
    'RandomForest': RandomForestClassifier(random_state=30),
    'GradientBoosting': GradientBoostingClassifier(random_state=30)
}

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [24]:
for model_name,model in models.items():
    model.fit(X_train,y_train)
    prediction=model.predict(X_test)
    score=accuracy_score(y_test,prediction)
    cm=confusion_matrix(y_test,prediction)
    print(prediction)
    print('score :',score)
    print('matrix :', cm)
    

['Malaria' 'Cervical spondylosis' 'Hepatitis D' ... 'Migraine'
 'Hyperthyroidism' 'Bronchial Asthma']
score : 1.0
matrix : [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]
['Malaria' 'Cervical spondylosis' 'Hepatitis D' ... 'Migraine'
 'Hyperthyroidism' 'Bronchial Asthma']
score : 1.0
matrix : [[34  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 26 ...  0  0  0]
 ...
 [ 0  0  0 ... 39  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 40]]


In [25]:
## according to runtime the gradientboosting is taking more time so 
##going for randomforest

In [99]:
randomforest=RandomForestClassifier(random_state=30)
randomforest.fit(X_train,y_train)
randomforest.predict(X_test)
score=accuracy_score(y_test,prediction)
print(score)

1.0


In [28]:
##accuracy is 100% 

In [100]:
import pickle
pickle.dump(randomforest,open('../models/randomforest.pkl','wb'))
#to make model

In [101]:
randomforest=pickle.load(open('../models/randomforest.pkl','rb'))

In [39]:
symptom=pd.read_csv('../Datasets/symtoms_df.csv')
symptom

Unnamed: 0                                  Disease  \
0              0                         Fungal infection   
1              1                         Fungal infection   
2              2                         Fungal infection   
3              3                         Fungal infection   
4              4                         Fungal infection   
...          ...                                      ...   
4915        4915  (vertigo) Paroymsal  Positional Vertigo   
4916        4916                                     Acne   
4917        4917                  Urinary tract infection   
4918        4918                                Psoriasis   
4919        4919                                 Impetigo   

                 Symptom_1              Symptom_2              Symptom_3  \
0                  itching              skin_rash   nodal_skin_eruptions   
1                skin_rash   nodal_skin_eruptions    dischromic _patches   
2                  itching   nodal_skin_eruptions    dischromic _patches   
3                  itching              skin_rash    dischromic _patches   
4                  itching              skin_rash   nodal_skin_eruptions   
...                    ...                    ...                    ...   
4915              vomiting               headache                 nausea   
4916             skin_rash     pus_filled_pimples             blackheads   
4917   burning_micturition     bladder_discomfort    foul_smell_of urine   
4918             skin_rash             joint_pain           skin_peeling   
4919             skin_rash             high_fever                blister   

                      Symptom_4  
0           dischromic _patches  
1                           NaN  
2                           NaN  
3                           NaN  
4                           NaN  
...                         ...  
4915         spinning_movements  
4916                   scurring  
4917   continuous_feel_of_urine  
4918        silver_like_dusting  
4919       red_sore_around_nose  

[4920 rows x 6 columns]

In [40]:
precuation=pd.read_csv('../Datasets/precautions_df.csv')

In [36]:
precuation

Unnamed: 0                                  Disease  \
0            0                            Drug Reaction   
1            1                                  Malaria   
2            2                                  Allergy   
3            3                           Hypothyroidism   
4            4                                Psoriasis   
5            5                                     GERD   
6            6                      Chronic cholestasis   
7            7                              hepatitis A   
8            8                          Osteoarthristis   
9            9  (vertigo) Paroymsal  Positional Vertigo   
10          10                             Hypoglycemia   
11          11                                     Acne   
12          12                                Diabetes    
13          13                                 Impetigo   
14          14                            Hypertension    
15          15                      Peptic ulcer diseae   
16          16             Dimorphic hemmorhoids(piles)   
17          17                              Common Cold   
18          18                              Chicken pox   
19          19                     Cervical spondylosis   
20          20                          Hyperthyroidism   
21          21                  Urinary tract infection   
22          22                           Varicose veins   
23          23                                     AIDS   
24          24             Paralysis (brain hemorrhage)   
25          25                                  Typhoid   
26          26                              Hepatitis B   
27          27                         Fungal infection   
28          28                              Hepatitis C   
29          29                                 Migraine   
30          30                         Bronchial Asthma   
31          31                      Alcoholic hepatitis   
32          32                                 Jaundice   
33          33                              Hepatitis E   
34          34                                   Dengue   
35          35                              Hepatitis D   
36          36                             Heart attack   
37          37                                Pneumonia   
38          38                                Arthritis   
39          39                          Gastroenteritis   
40          40                             Tuberculosis   

                            Precaution_1                        Precaution_2  \
0                        stop irritation            consult nearest hospital   
1               Consult nearest hospital                     avoid oily food   
2                         apply calamine             cover area with bandage   
3                          reduce stress                            exercise   
4       wash hands with warm soapy water        stop bleeding using pressure   
5                 avoid fatty spicy food       avoid lying down after eating   
6                             cold baths                  anti itch medicine   
7               Consult nearest hospital                  wash hands through   
8                          acetaminophen            consult nearest hospital   
9                               lie down         avoid sudden change in body   
10                      lie down on side                      check in pulse   
11                            bath twice              avoid fatty spicy food   
12                    have balanced diet                            exercise   
13      soak affected area in warm water                     use antibiotics   
14                            meditation                          salt baths   
15                avoid fatty spicy food              consume probiotic food   
16                avoid fatty spicy food                 consume witch hazel   
17           drink vitamin c rich drinks                         take vapour   
18   

In [38]:
description=pd.read_csv('../Datasets/description.csv')
diet=pd.read_csv('../Datasets/diets.csv')
workout=pd.read_csv('../Datasets/workout_df.csv')
medication=pd.read_csv('../Datasets/medications.csv')

In [109]:
workout

Unnamed: 0.1  Unnamed: 0           disease  \
0               0           0  Fungal infection   
1               1           1  Fungal infection   
2               2           2  Fungal infection   
3               3           3  Fungal infection   
4               4           4  Fungal infection   
..            ...         ...               ...   
405           405         405          Impetigo   
406           406         406          Impetigo   
407           407         407          Impetigo   
408           408         408          Impetigo   
409           409         409          Impetigo   

                               workout  
0                   Avoid sugary foods  
1                   Consume probiotics  
2            Increase intake of garlic  
3               Include yogurt in diet  
4                Limit processed foods  
..                                 ...  
405  Consult a healthcare professional  
406     Follow medical recommendations  
407                   Avoid scratching  
408        Take prescribed antibiotics  
409                Practice wound care  

[410 rows x 4 columns]

In [41]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


In [106]:
def predict_disease(symp):
    input_array=np.zeros(len(symptoms_dict))
    
    for item in symp:
        input_array[symptoms_dict[item]]=1
        predict_d=randomforest.predict([input_array])[0]
    return predict_d
    
    

In [108]:
symptom=input('Enter : ')
usersypmtom=[s.strip() for s in symptom.split(',')]
usersypmtom=[sym.strip("[]' ") for sym in usersypmtom]
print(usersypmtom)
predicted=predict_disease(usersypmtom)
print(predicted)


Enter : shivering,itching,skin_rash
['shivering', 'itching', 'skin_rash']
Fungal infection


E:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
E:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
E:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [120]:

def helper(dis):
    descr= description[description['Disease']==dis]['Description']
    descr=" ".join([w for w in descr])
    prec=precuation[precuation['Disease']==dis][['Precaution_1','Precaution_2','Precaution_3','Precaution_4']];
    prec=[col for col in prec.values]
    med=medication[medication['Disease']==dis]['Medication']
    med= [med for med in med.values]
    die=diet[diet['Disease']==dis]['Diet']
    die=[col for col in die.values]
    work=workout[workout['disease']==dis]['workout']
    return descr,prec,med,die,work


In [121]:
symptom=input('Enter : ')
usersypmtom=[s.strip() for s in symptom.split(',')]
usersypmtom=[sym.strip("[]' ") for sym in usersypmtom]
print(usersypmtom)
predicted=predict_disease(usersypmtom)
descr,prec,med,die,work=helper(predicted)

Enter : itching,shivering,skin_rash
['itching', 'shivering', 'skin_rash']


E:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
E:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
E:\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [122]:
print(predicted)
print(descr)
print(prec)
print(med)
print(die)
print(work)

Fungal infection
Fungal infection is a common skin condition caused by fungi.
[array(['bath twice', 'use detol or neem in bathing water',
       'keep infected area dry', 'use clean cloths'], dtype=object)]
["['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']"]
["['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']"]
0           Avoid sugary foods
1           Consume probiotics
2    Increase intake of garlic
3       Include yogurt in diet
4        Limit processed foods
5                Stay hydrated
6            Consume green tea
7       Eat foods rich in zinc
8     Include turmeric in diet
9    Eat fruits and vegetables
Name: workout, dtype: object
